### ISSUE TITLE
[Feature Request] Option to Default the Pause Button To Play

### ISSUE THREAD

**Issue by kanjieater** [Renji-XD/texthooker-ui#12]
![image](https://user-images.githubusercontent.com/32607317/217853767-192d8807-ee9a-41d1-b0b3-7a6c486df413.png)
As a power user, I only use the text counting and would like to be able to hook text immediately when the page loads, without any additional clicks. 

I tried modifying the code to default to the play state, however it seems this breaks the Reset Lines functionality. The lines can be cleared, but then adding more data from the clipboard & then refreshing the page brings back all the deleted lines.

**Comment by Renji-XD** [comment]
Do you care to have it only start automatically on page load or would any auto unpause ok? because in the latter case the "Autostart Timer during Pause" would proably have a close effect (meaning auto start as soon as the first line hits)

**Comment by kanjieater** [comment]
Since it says autostart timer, I didn't even think of it since I'm not using the timer, so good point. 

I do use the pause button to stop grabbing text though if I'm off doing something else. 
I also use a modified version of clipboard inserter to just insert automatically too - but I can I can just use that to stop adding clipboard data for now. 

I'll try that out for now - thanks!
