### ISSUE TITLE
[Feature Request] Disallow automatically grabbing from clipboard what was just copied from the page

### ISSUE THREAD

**Issue by kanjieater** [Renji-XD/texthooker-ui#19]
This is another feature the anacreon texthooker had that was handy. If you copy a word from a sentence to look it up on google images, it copies the word again to the page if the clipboard listener is enabled. 

I'd request that if you copy something from the t-ui page, it doesn't add it to your lines.

**Comment by kanjieater** [comment]
@Renji-XD It seems like this actually blocks you from being able to copy anything from the page as currently implemented. Could we revisit this? The desired behavior would be to allow copying still, but not add it to your lines.

**Comment by Renji-XD** [comment]
ya right. i think the closest thing i can do is skipping the next line from clipboard monitor after copy - guess it can theoretically have racing conditions when copying text while there is a (quick) stream of text coming from clipboard monitor but thats good enough for me right now
