### ISSUE TITLE
General Ideas on Easing Context/Content Switching

### ISSUE THREAD

**Issue by kanjieater** [Renji-XD/texthooker-ui#29]
First off, thanks for the profiles - I'm trying it out now & it simplifies things significantly. The post got long, I just wanted to keep context of why I think changes might be helpful rather than blunt requests. I'm happy to discuss this on discord or other means if you'd rather do that than read a wall of text.

On a personal note, while I forked the repo to make this a little easier on myself, at this point, all of the features I care about are already inside of here so I'm looking at how to get back onto the base project again. Thanks for the work on this project 🌮 

Since I usually switch between a few VNs & audiobooks while using the texthooker-ui, the two things I use the most are switching profiles (particularly adjusting the titles & vertical layout) & clearing the text. 

![image](https://user-images.githubusercontent.com/32607317/222832493-a6d0bbd2-957c-4f1e-bcb1-bc0bc00c5f21.png)
I configured it to look like this. 

From what I've been playing with here are the important things, I'd ask if we could consider a few of the following ideas:

A. Switching profiles easily
B. Clearing all text button
C. Clearing all text less verbose confirmation action
D. Action buttons order
E. Keep action buttons persistent

A. Switching profiles easily

If we could have an option to display the dropdown at that menu bar level it would be useful. In the picture above there's also an input to modify the title on the fly, but honestly just having it exposed in the settings is good enough. So something like this would suffice:
![image](https://user-images.githubusercontent.com/32607317/222832921-b63b58b7-74b9-4d7d-ade6-2d0e9d5a90b0.png)

B. Clearing all text button

The other part is the clearing text, which I use the red trashcan icon. Instead of making it give a prompt I just made it so it was red & dblclick:
https://github.com/kanjieater/texthooker-ui/blob/af1bad12ef8483a3a6bb6d886c2766f8792f1771/src/components/App.svelte#L278

C. Clearing all text less verbose confirmation action

For something you do multiple times in a day, confirming it gets tedious on clear. So if we could either make it optional or wire up some hotkeys so we could clear and confirm easily that'd be awesome. I'm not sure if other people would want to choose what type of clear they want to perform from the top level (I don't use the in-page timer so maybe most people would want to clear that too?)

D. Action buttons order

![image](https://user-images.githubusercontent.com/32607317/222835649-034dd7f2-5d7c-4baa-96a7-f0e96dd198b2.png)

If we were able to move a "clear all lines" trash icon out to the main, I'd also recommend sorting them in the order of action: `Clear a line`, `undo clear`, `clear all lines`. (`notes` & `Play` could go either before or after). Reason being, it's normal to clear a handful of lines and having the `clear a line` next to the `clear all lines` was more likely to have someone misclick `clear all lines`. Also I'm using the mdiCloseCircle for clear a line - I think this helps keep it distinct from the other trashcan icons in the app.

E. Keep action buttons persistent

One of the things I did notice was that if we make the `clear line` & `undo` buttons persistent, it helps with any misclicks. If the buttons disappear based on the lines shown it's easy to click `undo clear` twice for instance, when you only had one `undo clear` left, leading to misclicking. The solution here would be just always show them, regardless of if the lines and undo-able things are there are not. I think this was how anacreon's worked too.

Happy to help or clarify any of this. I can also break it into separate issues if you'd prefer, just let me know.

**Comment by Renji-XD** [comment]
A: Can be a new option - i assume it distracts people / mobile especially if they are not using it

B / C: As i wrote in the faq it was not intended to be used for mobile.. but while i have no specific plans to adjust the ui for now i probably also not want to work against it.. so i prefer two keybinds which respectively can trigger the reset lines / reset data functionality from the settings instead of moving the icon to the menu. For the confirmation then a new option

D: Will change the order - though i will keep the icon for now as i will not move the requested ones to the menu and in the settings they have labels

E: Sounds reasonable
