### ISSUE TITLE
Enable HTTP for github pages for remote access

### ISSUE THREAD

**Issue by xy2iii** [Renji-XD/texthooker-ui#3]
If the domain the texthooker ui is served from is HTTPS, then Chrome/Firefox requires all non local connection to be web socket secure connections (basically websocket over TLS).

This means that trying to connect using this page to, for example a server on the same network, will fail, but only if the page is served as HTTPS. If served as HTTP it works fine.

In a guide to texthook from phone https://rentry.co/android-texthook I hosted the page as HTTP as a workaround.

My question is, would it be possible to enable HTTP for github pages?

**Comment by Renji-XD** [comment]
Hi,

github pages are enforced to run with https - and i have no custom domain to point to. As i see you hare hosting a version on surge but just for your information i think these 2 alternatives should also work:

- Download the index.html from docs folder in your mobile browser and open it
- Clone the repository and serve via local server (added command and notice to the readme)

That said more importantly is the fact that the page was not built with small form factors / mobile in mind... so the current ui probably will not be as good as it could be and some things will be also missing as they are bound to keybinds (like selecting lines for deletion etc.) ;) I may work on it some day but feel to to open prs in case you want to follow your approach and work on some things in the meanwhile

Therefore closing this issue as for now i don't see any open point : )
