### ISSUE TITLE
[Feature Request] Easier Way Dismiss Confirmations 

### ISSUE THREAD

**Issue by kanjieater** [Renji-XD/texthooker-ui#32]
Specifically I'm thinking of the websocket confirmations, though this could probably be applied broadly to the ones that don't involve user interaction (Presets). Sometimes it's expected that the websocket disconnects when you close MPV to open a different file or VN. 

Currently you have to click the confirm button, but I was hoping we could do some or multiple of the following:
- Toast style: Just dismisses itself after a time
- Any click dismisses: Clicking outside the confirmation could also dismiss it
- Hotkey dismisses confirmations

**Comment by Renji-XD** [comment]
Actually i think this is exclusively for the websocket message

Timed Toast: Not sure if an user would wait e. g. 3 seconds if he simply can click it away anyways (especially with subsequent prompts)

Click Dismiss: Most of the Prompts have a cancel or confirm action attached. For them you can skip the confirmation already via options (which is probably the more executed action). So a click dismiss would be actually just for the websocket disconnect

Hotkey: Not available for mobile, also same as previous point

I have the feeling this is a really specifc issue for mpv / you as for most users of vns i would expect the websocket to stay connected and or not happening that often that moving the mouse half of your screen would feel annoying. Probably it would be in general also anyways cleaner if e. g. mpv_websocket emits a custom close event which could be handled and then gracefully closes the connection on client side... or you just enable the mpv setting to keep the program open on file end... which i guess would also not kill the websocket server 

therefore i tend to close this issue this time without a change ; )
