### ISSUE TITLE
WSL2 Ubuntu 22.04.2 LTS package conflicts

### ISSUE THREAD

**Issue by spirited1086** [Renji-XD/texthooker-ui#34]
Hi, I know this is not really an issue with your program, but hoping I can have some clues on how to fix this. I've installed python 3.9.9 by compiling from source and then ran 'python3.9 -m pip install -r requirements.txt --user.' I've doubled checked that the python3.9 binary is python 3.9.9.

However, when I run this I get:
```
**ERROR: Cannot install openai-whisper and requests==2.23.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested requests==2.23.0
    tiktoken 0.3.1 depends on requests>=2.26.0**

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
``` 

I've actually also tried running this  pip installwith later version of Python and I'm having the same issue.

**Comment by Renji-XD** [comment]
Hi,

i would be glad to help you but i don't even have an idea what you are trying to install (looks like whisper?) nor why you have choosen this repository which has not even a single python component xD

I would recommend to try open a support question in the repo for whatever app you are trying to install or to raise a question in general forums like stackexchange - i would assume you will get a quicker response there than from me ; )

**Comment by spirited1086** [comment]
Wrong repo, sorry.
