### ISSUE TITLE
[Feature request] Second websocket connection

### ISSUE THREAD

**Issue by AuroraWright** [Renji-XD/texthooker-ui#41]
Maybe a bit of an edge case, but as I have my own background OCR tool which can write text to a websocket (https://github.com/AuroraWright/owocr for what it's worth) and I mostly use it whenever there's a sentence/word that's not covered by subtitles or extracted text in a VN (like text in an image), as-is I basically need to use the clipboard, or switch profiles whenever I need to OCR something. It would be nice if there was a way to have a second connection for this purpose.
Also, thank you for your work!

**Comment by AuroraWright** [comment]
Gave it a try and implemented it for personal usage: https://github.com/AuroraWright/texthooker-ui/commit/663b861b79ad2159b9ed2f081a8c8336512db435
(I've never touched svelte/typescript before so it might not be the cleanest implementation), I'm open to make a pull request if you are interested

**Comment by Renji-XD** [comment]
Hi, 

i actually also have a local version already (very close to yours) - i just hadn't the time to test it. 

I will probably merge it in the next day(s) ; )
