### ISSUE TITLE
Messages from websocket are not showing up

### ISSUE THREAD

**Issue by ThisIsntTheWay** [Renji-XD/texthooker-ui#44]
Using mpv with [`kuroahna/mpv_websocket`](https://github.com/kuroahna/mpv_websocket), the page is able to connect to the WS but seemingly unable to display incoming messages:
![image](https://github.com/Renji-XD/texthooker-ui/assets/13659371/351bce37-fb95-4c89-a33f-fea9493db27c)

Whenever a message is received, the page briefly flashes but fails to display anything.  
This happens in both Chrome and Firefox.

**Comment by Renji-XD** [comment]
hi,

by default lines will only be shown when the timer runs (flashing is basically an indicator you missed a line). You can disable it via respective setting or let the timer autostart

![image](https://github.com/Renji-XD/texthooker-ui/assets/6409827/b3d43794-3919-414f-a216-ed0f11668d5b)
