### ISSUE TITLE
Improvements to AFK

### ISSUE THREAD

**Issue by pinntokuru** [Renji-XD/texthooker-ui#47]
It would be great if it was possible to pause/restart the timer by double clicking on the page like in exSTATic, as well as have the page become blurry as a quick way to indicate the timer is stopped.

Going further than existing exSTATic functions, however, how about auto resetting the AFK timer to zero if the user mover the cursor over a line? This is something I encounter a lot when mining longer than usual lines. The AFK timer runs out and the timer stops even though I'm still reading/using Yomitan to look up words. If an event like "mousemove" is listened to over a line while the timer is already active then chances are the user is actively reading the line. If I try to increase the AFK timer limit to cover these long lines then I have to manually deactivate for most of the other lines.

**Comment by Renji-XD** [comment]
hi,

the first point can certainly be added as new option.

the second point is only partially possible. While it is possibly (with some settings disabled in yomitan) to detect if it is open or not it is stealing the focus from the site so event listeners will not fire and as a chrom extension iframe it is not possible to listen to events inside the popup. So max is to either reset the afk timer once per open/close/move position of the popup (probably my preference) or by completely disabling the afk timer as long as its open (and accepting that the timer will keep running when going afk and popup is open)

**Comment by pinntokuru** [comment]
> the second point is only partially possible. While it is possibly (with some settings disabled in yomitan) to detect if it is open or not it is stealing the focus from the site so event listeners will not fire and as a chrom extension iframe it is not possible to listen to events inside the popup. So max is to either reset the afk timer once per open/close/move position of the popup (probably my preference) or by completely disabling the afk timer as long as its open (and accepting that the timer will keep running when going afk and popup is open)

I think you misunderstood my second idea. I was not really suggesting recognizing the Yomitan popup, just the presence of the mouse cursor over anywhere in the page. So in one sentence my suggestion is "**don't stop the timer as long as the mouse cursor is moving on the texthooker page**." I think that should be possible if double click pause is possible, since it's simply listening to a mouse move event instead of a double click event.

**Comment by Renji-XD** [comment]
no i got it - and it is already existing.. but as you said you are using yomitan so i explained why using it can break it and what alternatives exist.

Try to set the afk timer to e. g. 10 seconds, start the timer and move the mouse around the page every 5 seconds (without yomitan scanning). You should see that the timer will run over 10 seconds - then stop and roughly 10 seconds later it should pause.

now do the same and just move the cursor around inside the yomitan popup - you should see that afk timer pauses after 10 seconds even if you moved for the reasons i shared. 

If you move the cursor outside of the yomitan popup it should also work - if that is already sufficient for you i don't see any open point for implementation
