### ISSUE TITLE
Timer is slower than real time

### ISSUE THREAD

**Issue by xy2iii** [Renji-XD/texthooker-ui#7]
I had the impression the timer was running slow. 

Then I tried measuring this page, https://www.timer-tab.com/ on another tab and my phone timer for 1 hour. I got these times:

- timer-tab and phone: 1:00:00
- texthooker-ui: 44:53

It seems the timer runs slow. Is it possible to fix it?

**Comment by Renji-XD** [comment]
just to confirm - you started the texthooker and then switched to the other tabs?

in that case you may encountered background throtteling/timer drifting. most browser stop or throttel interval executions when a page is not visible for the user for a specific time period (e. g. 5 minutes). The timer was a one by one incrementer which means if ticks are skipped the value can get wrong.. did not considered such cases as important tbh

If you say the timer is also wrong when the page is focused i probably need some more details of how your environment looks like (e. g. # of stored lines, settings etc.) as i don't see any difference between the page and a separate timer when checking

i also pushed a change to the timer to change how the value is caluclated.. maybe that will already be sufficient for your case.. let me know

**Comment by xy2iii** [comment]
Based, thank you
