### ISSUE TITLE
[Bug] No flash or lines collected if settings menu is open

### ISSUE THREAD

**Issue by kanjieater** [Renji-XD/texthooker-ui#9]
Lines should probably continue to collect even if the menu is open. It might also be good to automatically close the window in such a case (and flash if it's enabled ) to get the user's attention.

EDIT: The same is true for editing text too - we'd probably want to update that as well.

**Comment by Renji-XD** [comment]
iirc that was actually kind of wanted - currently there is no differentiation between the sources from which a text comes from.. but without that you would either get lines inserted to the page or flashing when e. g. pasting sth to the settings menu/while editing - and i saw those as times where typically anways no new text would appear so i choose the quicker way : >

if you think that it is more common that there is a continous stream of text even in such scenarios i may can check for such a change i described and consider to block new lines only for paste cases when settings are open / line is in editing while flashing for other sources

**Comment by kanjieater** [comment]
Yeah, that's a good point. I know I've left the menu open at this point already and been surprised to look over and see it open and missing lines. 

I think it's probably worth making sure the user isn't losing lines though. I'm guessing pasting stuff into the settings is actually less common, since you're only do it with custom css & maybe a port for sockets here and there.
